php-fpm:
    build: php-fpm
    ports:
        - 9000:9000
    volumes:
        - ./app:/var/www/html/
nginx:
    build: nginx
    ports:
        - 8080:80
    volumes:
        - ./app:/var/www/html/        
    links:
        - php-fpm
